
name: ci-golang-workflow
on:
  # push:
  #   branches:
  #     - main
  #     - develop
  pull_request:
    branches:
      - develop
   
jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # go-version: [1.23, 1.24]
        go-version: [1.24]
        os: [ubuntu-latest] # ,"ubuntu-arm64-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Run Go App
        run: go run cmd/math.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.prod
          platforms: linux/amd64,linux/arm64
          push: false
          tags: fpessoa64/ci-go:${{ matrix.go-version }}-${{ matrix.os }}