
name: ci-golang-workflow
on:
  # push:
  #   branches:
  #     - main
  #     - develop
  pull_request:
    branches:
      - develop
   
jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # go-version: [1.23, 1.24]
        go-version: [1.24]
        os: [ubuntu-latest,"ubuntu-arm64-latest"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Run Go App
        run: go run cmd/math.go